//
// DO NOT EDIT.
//
// Generated by the protocol buffer compiler.
// Source: gRPCBinding/models/mainScreen/main_screen.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import Dispatch
import Foundation
import SwiftGRPC
import SwiftProtobuf

internal protocol MainScreen_MainScreenUpdateLabelCall: ClientCallUnary {}

fileprivate final class MainScreen_MainScreenUpdateLabelCallBase: ClientCallUnaryBase<MainScreen_Entry, MainScreen_LabelValue>, MainScreen_MainScreenUpdateLabelCall {
  override class var method: String { return "/mainScreen.MainScreen/UpdateLabel" }
}


/// Instantiate MainScreen_MainScreenServiceClient, then call methods of this protocol to make API calls.
internal protocol MainScreen_MainScreenService: ServiceClient {
  /// Synchronous. Unary.
  func updateLabel(_ request: MainScreen_Entry, metadata customMetadata: Metadata) throws -> MainScreen_LabelValue
  /// Asynchronous. Unary.
  @discardableResult
  func updateLabel(_ request: MainScreen_Entry, metadata customMetadata: Metadata, completion: @escaping (MainScreen_LabelValue?, CallResult) -> Void) throws -> MainScreen_MainScreenUpdateLabelCall

}

internal extension MainScreen_MainScreenService {
  /// Synchronous. Unary.
  func updateLabel(_ request: MainScreen_Entry) throws -> MainScreen_LabelValue {
    return try self.updateLabel(request, metadata: self.metadata)
  }
  /// Asynchronous. Unary.
  @discardableResult
  func updateLabel(_ request: MainScreen_Entry, completion: @escaping (MainScreen_LabelValue?, CallResult) -> Void) throws -> MainScreen_MainScreenUpdateLabelCall {
    return try self.updateLabel(request, metadata: self.metadata, completion: completion)
  }

}

internal final class MainScreen_MainScreenServiceClient: ServiceClientBase, MainScreen_MainScreenService {
  /// Synchronous. Unary.
  internal func updateLabel(_ request: MainScreen_Entry, metadata customMetadata: Metadata) throws -> MainScreen_LabelValue {
    return try MainScreen_MainScreenUpdateLabelCallBase(channel)
      .run(request: request, metadata: customMetadata)
  }
  /// Asynchronous. Unary.
  @discardableResult
  internal func updateLabel(_ request: MainScreen_Entry, metadata customMetadata: Metadata, completion: @escaping (MainScreen_LabelValue?, CallResult) -> Void) throws -> MainScreen_MainScreenUpdateLabelCall {
    return try MainScreen_MainScreenUpdateLabelCallBase(channel)
      .start(request: request, metadata: customMetadata, completion: completion)
  }

}

/// To build a server, implement a class that conforms to this protocol.
/// If one of the methods returning `ServerStatus?` returns nil,
/// it is expected that you have already returned a status to the client by means of `session.close`.
internal protocol MainScreen_MainScreenProvider: ServiceProvider {
  func updateLabel(request: MainScreen_Entry, session: MainScreen_MainScreenUpdateLabelSession) throws -> MainScreen_LabelValue
}

extension MainScreen_MainScreenProvider {
  internal var serviceName: String { return "mainScreen.MainScreen" }

  /// Determines and calls the appropriate request handler, depending on the request's method.
  /// Throws `HandleMethodError.unknownMethod` for methods not handled by this service.
  internal func handleMethod(_ method: String, handler: Handler) throws -> ServerStatus? {
    switch method {
    case "/mainScreen.MainScreen/UpdateLabel":
      return try MainScreen_MainScreenUpdateLabelSessionBase(
        handler: handler,
        providerBlock: { try self.updateLabel(request: $0, session: $1 as! MainScreen_MainScreenUpdateLabelSessionBase) })
          .run()
    default:
      throw HandleMethodError.unknownMethod
    }
  }
}

internal protocol MainScreen_MainScreenUpdateLabelSession: ServerSessionUnary {}

fileprivate final class MainScreen_MainScreenUpdateLabelSessionBase: ServerSessionUnaryBase<MainScreen_Entry, MainScreen_LabelValue>, MainScreen_MainScreenUpdateLabelSession {}

